---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprraum
# description will be included in the image's metadata
description: This is my opinionated OS image based on Hyprland

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      copr:
        - lihaohong/yazi
        - lionheartp/Hyprland
      cleanup: true
    install:
      install-weak-deps: false
      packages:
        #config
        - stow

        # WM / session
        - hyprland
        - waybar
        - xdg-desktop-portal-hyprland
        - hyprpaper
        - hyprlock
        - hypridle
        - hyprland-qtutils
        # environment
        - qt5-qtwayland
        - qt6-qtwayland
        - wl-clipboard
        - xdg-desktop-portal-wlr
        - xdg-desktop-portal-gtk
        - xorg-x11-server-Xwayland
        - waybar
        - rofi
        - foot
        - cage
        - gtkgreet
        - gtklock
        - polkit
        - xfce-polkit
        - mako
        - wl-clipboard
        - swaybg
        - gnome-keyring

        # screenshot
        - slurp
        - grim

        # File management
        - thunar
        - thunar-archive-plugin
        - thunar-volman
        - file-roller
        - imv

        # CLI essentials
        - tmux
        - zsh
        - starship
        - neovim
        - yazi
        - git
        - curl
        - wget
        - ripgrep
        - fd-find
        - bat
        - fzf
        - eza
        - acpi
        - mpv

        # Useful desktop helpers
        - pavucontrol
        - brightnessctl
        - playerctl
        - network-manager-applet
        - blueman-applet
        - xdg-user-dirs

        # Printing
        - cups

    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.onlyoffice.desktopeditors
          - org.localsend.localsend_app
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: brew
    nofile-limits: true
    brew-analytics: false
  - type: script
    snippets:
      - "systemctl enable greetd.service"
      - "systemctl set-default graphical.target"
    scripts:
      - "install-jetbrainsmono-nerdfont.sh"
  - type: files
    files:
    - source: system/usr  # copies `files/system/*` (* means everything inside it) into your image's root folder `/`
      destination: /usr
    - source: system/etc  # copies `files/system/*` (* means everything inside it) into your image's root folder `/`
      destination: /etc
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
